node {
    stage ("Checkout DataApi"){
        git branch: 'develop', url: '/home/osboxes/MSDProject/projectRepo/msd-data-service-repo'
    }
    
    stage ("Gradle Build - DataApi") {
        sh 'gradle -b project-data-service/build.gradle clean build'
    }
    
    stage ("Gradle Bootjar-Package - DataApi") {
        sh 'gradle -b project-data-service/build.gradle bootjar'
    }

    stage('User Acceptance Test') {

	   def response= input message: 'Is this build good to go?',
	   parameters: [choice(choices: 'Yes\nNo', 
	   description: '', name: 'Pass')]
	
	  if(response=="Yes") {
	    stage('Deploy') {
	      sh 'gradle -b project-data-service/build.gradle build -x test'
        }
      }
    }	
}